import { Request, Response, NextFunction } from 'express';
import { DomainError } from '../../domain/errors';

// The only place DomainError.code is mapped to an HTTP status — keeps that
// mapping decision out of domain/ and application/ entirely.
const STATUS_BY_CODE: Record<string, number> = {
  INVALID_INPUT: 400,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  INVALID_REFRESH_TOKEN: 401,
  USERNAME_TAKEN: 409,
  CONCURRENT_MODIFICATION: 409,
  CHARACTER_NOT_FOUND: 404,
  INSUFFICIENT_LINH_KHI: 400,
  PUNISHED: 400,
  MAX_STAGE_REACHED: 400,
  PILL_NOT_FOUND: 404,
  PILL_OUT_OF_STOCK: 409,
  PILL_NOT_APPLICABLE: 400,
  FORBIDDEN: 403,
  INVALID_REALM_CONFIG: 400,
  INVALID_PILL_CONFIG: 400,
  PILL_ID_TAKEN: 409,
  USER_NOT_FOUND: 401,
  REDEEM_CODE_NOT_FOUND: 404,
  REDEEM_CODE_INACTIVE: 400,
  REDEEM_CODE_EXPIRED: 400,
  REDEEM_CODE_ALREADY_USED: 409,
  REDEEM_CODE_EXHAUSTED: 409,
  REDEEM_CODE_TAKEN: 409,
  INVALID_REDEEM_CODE: 400,
  CONGPHAP_NOT_FOUND: 404,
  CONGPHAP_NOT_OWNED: 404,
  CONGPHAP_NOT_EQUIPPABLE: 400,
  CONGPHAP_SLOT_INVALID: 400,
  CONGPHAP_MAX_LEVEL: 409,
  CONGPHAP_NOT_LEARNABLE: 400,
  CONGPHAP_REALM_GATE: 409,
  CONGPHAP_MISSING_BITICH: 409,
  CONGPHAP_ALREADY_OWNED: 409,
  INSUFFICIENT_LINH_THACH: 409,
  INVALID_CONGPHAP_CONFIG: 400,
  CONGPHAP_ID_TAKEN: 409,
  INVALID_GRANT: 400,
  INVALID_MATERIAL_CONFIG: 400,
  MATERIAL_NOT_FOUND: 404,
  ALCHEMY_RECIPE_INVALID: 400,
  ALCHEMY_QUEUE_INVALID: 400,
  ALCHEMY_RECIPE_NOT_FOUND: 404,
  INSUFFICIENT_MATERIALS: 409,
  ALCHEMY_RANK_TOO_LOW: 409,
  ALCHEMY_RANK_LOCKED: 409,
  ALCHEMY_RANK_INVALID: 400,
  ALCHEMY_REALM_GATE: 409,
  ALCHEMY_FURNACE_INVALID: 400,
  ALCHEMY_FURNACE_MAX: 409,
  INSUFFICIENT_DAN_KHI: 409,
  INVALID_COMBAT_CONFIG: 400,
  EXPEDITION_BRANCH_NOT_FOUND: 404,
  EXPEDITION_DIFFICULTY_NOT_FOUND: 404,
  EXPEDITION_NOT_FOUND: 404,
  INVALID_EXPEDITION_CONFIG: 400,
  INSUFFICIENT_EXPEDITION_TICKETS: 409,
  EXPEDITION_ACTIVE: 409,
  EXPEDITION_NOT_COMPLETE: 409,
  EXPEDITION_ALREADY_CLAIMED: 409,
};

export function errorHandler(err: unknown, _req: Request, res: Response, _next: NextFunction) {
  if (err instanceof DomainError) {
    const status = STATUS_BY_CODE[err.code] ?? 500;
    res.status(status).json({ error: { code: err.code, message: err.message } });
    return;
  }
  console.error(err);
  res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'Internal server error' } });
}
